### ISSUE TITLE
junit maven repository issue

### ISSUE THREAD

**Issue by batrap** [douglascraigschmidt/CS251#7]
I think the maven repository for junit should be junit:junit:4.11 instead of org.junit:com.springsource.org.junit:4.11.0 (in libraries/org_junit_com_springsource_org_junit_4_11_0.xml). I'm using intellij and it can't seem to find the springsource one

**Comment by wrotte** [comment]
You're probably correct.  Do you know how to formulate a pull request?

**Comment by batrap** [comment]
I'm not quite sure how to submit one from gitlab to github

**Comment by wrotte** [comment]
They're both git :-p

IOW, github shouldn't care, follow a similar procedure.
