### ISSUE TITLE
Spliterator test case

### ISSUE THREAD

**Issue by batrap** [douglascraigschmidt/CS251#9]
The spliterator test case isn't working properly for me. By default, the spliterator appears to split based on an arithmetic progression (1024, 2048, etc) instead of dividing the ListArray in half each time. It looks like the test case expects the latter behavior.

**Comment by batrap** [comment]
Also, one of the iterator tests tests for an ArrayIndexOutOfBoundsException instead of the NoSuchElementException that it's supposed to throw according to the interface

**Comment by wrotte** [comment]
I thought I'd deleted the spliterator. 

The tests were half baked in the first place. 

Don't worry about tit
